version: '3.9'

services:

  auth:
    container_name: auth
    env_file:
      - .\cmd\main\.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=glimpse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glimpse
      - POSTGRES_SSL_MODE=disable
      - API_ADDRESS=auth:8081
      - JWT_ACCESS_SECRET=secret
      - JWT_ACCESS_EXPIRATION=24h
      - JWT_REFRESH_SECRET=refresh_secret
      - JWT_REFRESH_EXPIRATION=720h
      - JWT_ISSUER=glimpse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: glimpse
      POSTGRES_USER: glimpse
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres
      - .\internal\adapters\postgres\migrations\tables.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge